### ISSUE TITLE
Create Hero details screen

### ISSUE THREAD

**Issue by sergdort** [sergdort/FunctionalMarvel#3]

**Comment by sergdort** [comment]
Hi, @RafaelPlantard , I wanted for a long time to create hero detail screen 
But I still don't have hole idea how it could look like
[Here](http://developer.marvel.com/docs) we can get hero by id
If you have any ideas how it could look like, I will be happy to discus :)

**Comment by RafaelPlantard** [comment]
Of course, we can start at next week, I will study more about Rx.
Let's go...
Maybe we can add your RxSegue class and just send my current view model selected (as context) with more details on Model class.
